script fixes again

diff --git a/scripts/.local/bin/tag b/scripts/.local/bin/tag
--- a/scripts/.local/bin/tag
+++ b/scripts/.local/bin/tag
@@ -1,64 +1,63 @@
 #!/bin/sh
 
-err() { echo "Usage:
-        tag [OPTIONS] file
-Options:
-        -a: artist/author
-        -t: song/chapter title
-        -A: album/book title
-        -n: track/chapter number
-        -N: total number of tracks/chapters
-        -d: year of publication
-        -g: genre
-        -c: comment
-You will be prompted for title, artist, album and track if not given." && exit 1 ;}
+usage()
+{
+	echo "usage: ${0##*/} [-a artist] [-A album_title] [-c comment]" 1>&2
+	echo "	[-d year] [-g genre] [-n trackno] [-N totalno]" 1>&2
+	echo "	[-t song_title] file" 1>&2
+	exit 1
+}
 
-while getopts "a:t:A:n:N:d:g:c:f:" o; do case "${o}" in
-        a) artist="${OPTARG}" ;;
-        t) title="${OPTARG}" ;;
-        A) album="${OPTARG}" ;;
-        n) track="${OPTARG}" ;;
-        N) total="${OPTARG}" ;;
-        d) date="${OPTARG}" ;;
-        g) genre="${OPTARG}" ;;
-        c) comment="${OPTARG}" ;;
-        f) file="${OPTARG}" ;;
-        *) printf "Invalid option: -%s\\n" "$OPTARG" && err ;;
-esac done
+xread()
+{
+        printf "%s" "${1}" && read -r ${2}
+}
 
+while getopts "a:t:A:n:N:d:g:c:f:" arg; do
+case "${arg}" in
+	a) artist="${OPTARG}" ;;
+	t) title="${OPTARG}" ;;
+	A) album="${OPTARG}" ;;
+	n) track="${OPTARG}" ;;
+	N) total="${OPTARG}" ;;
+	d) date="${OPTARG}" ;;
+	g) genre="${OPTARG}" ;;
+	c) comment="${OPTARG}" ;;
+	f) file="${OPTARG}" ;;
+	*) usage ;;
+esac
+done
 shift $((OPTIND - 1))
 
-file="$1"
+file="${1}"
+test ! -f "${file}" && echo "${0##*/}: file not found" && usage
 
-[ ! -f "$file" ] && echo "Provide file to tag." && err
-[ -z "$title" ] && echo "Enter a title." && read -r title
-[ -z "$artist" ] && echo "Enter an artist." && read -r artist
-[ -z "$album" ] && echo "Enter an album." && read -r album
-[ -z "$track" ] && echo "Enter a track number." && read -r track
+test -z "${title}" && xread "Title: " title
+test -z "${artist}" && xread "Artist: " artist
+test -z "${album}" && xread "Album: " album
+test -z "${track}" && xread "Track number: " track
 
-case "$file" in
-        *.mp3) echo "Title=$title
-Artist=$artist
-Album=$album
-Track=$track
-Total=$total
-Date=$date
-Genre=$genre
-Comment=$comment
-        *.mp3) echo "Title=$title
-Artist=$artist
-Album=$album
-Track=$track
-Total=$total
-Date=$date
-Genre=$genre
-Comment=$comment ;;
-        *.mp3) eyeD3 -Q --remove-all \ 
-        -a "$artist" \ 
-        -A "$album" \
-        -t "$title" \
-        -n "$track" \
-        -N "$total" \
-        -Y "$date" "$file" ;;
-        *) echo "File type not implemented yet." ;;
+info="Title=${title}
+Artist=${artist}
+Album=${album}
+Track=${track}
+Total=${total}
+Date=${date}
+Genre=${genre}
+Comment=${comment}"
+
+echo "${info}"
+
+case "${file}" in
+	*.ogg)	echo "${info}" | vorbiscomment -w "${file}" ;;
+	*.opus)	echo "${info}" | opustags -i -S "${file}" ;;
+	*.mp3)	eyeD3 -Q --remove-all \
+			-a "${artist}" \
+			-A "${album}" \
+			-t "${title}" \
+			-n "${track}" \
+			-N "${total}" \
+			-Y "${date}" \
+			"${file}" ;;
+	*)	echo "${0##*/}: file type not implemented yet" ;;
 esac
